# Generated by CMake, DO NOT EDIT
/Users/zhangpeng/rtmp/crtmpserver/builders/xcode/CMakeFiles/cmake.check_cache: \
/Users/zhangpeng/rtmp/crtmpserver/builders/cmake/thelib/CMakeLists.txt
	/usr/local/Cellar/cmake28/2.8.12.2/bin/cmake -H/Users/zhangpeng/rtmp/crtmpserver/builders/cmake -B/Users/zhangpeng/rtmp/crtmpserver/builders/xcode
