# Generated by CMake, DO NOT EDIT
/Users/zhangpeng/rtmp/crtmpserver/builders/xcode/CMakeFiles/cmake.check_cache: \
/Users/zhangpeng/rtmp/crtmpserver/builders/cmake/applications/CMakeLists.txt\
/Users/zhangpeng/rtmp/crtmpserver/builders/cmake/applications/admin/CMakeLists.txt\
/Users/zhangpeng/rtmp/crtmpserver/builders/cmake/applications/appselector/CMakeLists.txt\
/Users/zhangpeng/rtmp/crtmpserver/builders/cmake/applications/flvplayback/CMakeLists.txt\
/Users/zhangpeng/rtmp/crtmpserver/builders/cmake/applications/proxypublish/CMakeLists.txt\
/Users/zhangpeng/rtmp/crtmpserver/builders/cmake/applications/samplefactory/CMakeLists.txt\
/Users/zhangpeng/rtmp/crtmpserver/builders/cmake/applications/stresstest/CMakeLists.txt\
/Users/zhangpeng/rtmp/crtmpserver/builders/cmake/applications/vptests/CMakeLists.txt
	/usr/local/Cellar/cmake28/2.8.12.2/bin/cmake -H/Users/zhangpeng/rtmp/crtmpserver/builders/cmake -B/Users/zhangpeng/rtmp/crtmpserver/builders/xcode
